variable "cidr_blk" {}
variable "public_A_subnet" {}
variable "private_A_subnet" {}
variable "public_B_subnet" {}
variable "private_B_subnet" {}
variable "ALB_SG" {}
variable "vault_SG" {}
variable "jenkins_SG" {}
variable "vault_TG" {}
variable "jenkins_TG" {}